# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproifle',
            name='brief',
            field=models.CharField(default='这个人很懒，什么也没有留下...', max_length=128),
        ),
        migrations.AddField(
            model_name='userproifle',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userproifle_friends_+', to='app01.UserProifle'),
        ),
    ]
