# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0002_auto_20170405_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bref', models.CharField(blank=True, max_length=128, null=True)),
                ('notification', models.CharField(blank=True, max_length=128, null=True, verbose_name='群公告')),
                ('max_members', models.PositiveSmallIntegerField(default=200)),
                ('members', models.ManyToManyField(to='app01.UserProifle')),
            ],
        ),
    ]
