# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=64)),
                ('passwd', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
